/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controller.Controller;
import exception.FimDeJogoException;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import model.Pergunta;

/**
 *
 * @author gabrielantonio
 */

public class Jogo extends javax.swing.JFrame {

    JLabel ultimo_label;
    FinalDeJogoDialog finalDeJogoDialog;
    RespostaEmBrancoDialog respostaEmBrancoDialog;
    RespostaCertaMacaco respostaCertaMacaco;
    RespostaErradaMacaco respostaErradaMacaco;
    boolean certa = false;
    int resposta_marcada = -1;
    Controller cont;
    Pergunta perguntaAtual;
    /**
     * Creates new form Jogo
     */
    public Jogo() {
        
        
        initDialogs();
        initComponents();
        setLocationRelativeTo(null);
        proxima_pergunta.setBackground(Color.GREEN);
        //proxima_pergunta.setOpaque(true);
        setResizable(false);
        cont = Controller.getInstancia();
        cont.initDados();
        try {
            perguntaAtual = cont.ProximaPergunta();
        } catch (FimDeJogoException ex) {
            Logger.getLogger(Jogo.class.getName()).log(Level.SEVERE, null, ex);
        }
        bindingPergunta();
    }
    
    private void limpar(){
        resposta_marcada = -1;
        resposta1.setSelected(false);
        resposta2.setSelected(false);
        resposta3.setSelected(false);
        resposta4.setSelected(false);
    }
    
    private void bindingPergunta(){
        pergunta.setText(perguntaAtual.getTexto());
        resposta1.setText(perguntaAtual.getRespostas()[0]);
        resposta2.setText(perguntaAtual.getRespostas()[1]);
        resposta3.setText(perguntaAtual.getRespostas()[2]);
        resposta4.setText(perguntaAtual.getRespostas()[3]);
        
        limpar();
        
        if(perguntaAtual.getImagem() != null){
            JLabel label = new JLabel(perguntaAtual.getImagem());
            label.setBounds(0, 0, 257, 272);
            imagem.removeAll();
            imagem.add(label);
            imagem.setVisible(true);
        } else{
            imagem.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        resposta1 = new javax.swing.JRadioButton();
        resposta2 = new javax.swing.JRadioButton();
        resposta3 = new javax.swing.JRadioButton();
        resposta4 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pergunta = new javax.swing.JTextArea();
        proxima_pergunta = new javax.swing.JButton();
        imagem = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        resposta1.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        resposta1.setText("jRadioButton1");
        resposta1.setActionCommand("resposta1");
        resposta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resposta1ActionPerformed(evt);
            }
        });

        resposta2.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        resposta2.setText("jRadioButton2");
        resposta2.setActionCommand("resposta2");
        resposta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resposta2ActionPerformed(evt);
            }
        });

        resposta3.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        resposta3.setText("jRadioButton3");
        resposta3.setActionCommand("resposta3");
        resposta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resposta3ActionPerformed(evt);
            }
        });

        resposta4.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        resposta4.setText("jRadioButton4");
        resposta4.setActionCommand("resposta4");
        resposta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resposta4ActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(238, 238, 238));
        jScrollPane1.setBorder(null);

        pergunta.setEditable(false);
        pergunta.setBackground(new java.awt.Color(238, 238, 238));
        pergunta.setColumns(22);
        pergunta.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        pergunta.setForeground(new java.awt.Color(0, 153, 0));
        pergunta.setLineWrap(true);
        pergunta.setRows(5);
        pergunta.setText("exemplo 238,238,238 exemplo 238,238,238exemplo 238,238,238exemplo 238,238,238exemplo 238,238,238exemplo 238,238,238exemplo 238,238,238exemplo 238,238,238exemplo 238,238,238exemplo 238,238,238exemplo 238,238,238exemplo 238,238,238exemplo 238,238,238exemplo 238,238,238exemplo 238,238,238exemplo 238,238,238exemplo 238,238,238exemplo 238,238,238");
        pergunta.setToolTipText("");
        pergunta.setBorder(null);
        jScrollPane1.setViewportView(pergunta);

        proxima_pergunta.setBackground(new java.awt.Color(102, 255, 0));
        proxima_pergunta.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        proxima_pergunta.setForeground(new java.awt.Color(255, 255, 255));
        proxima_pergunta.setText("PRÓXIMA");
        proxima_pergunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proxima_perguntaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout imagemLayout = new javax.swing.GroupLayout(imagem);
        imagem.setLayout(imagemLayout);
        imagemLayout.setHorizontalGroup(
            imagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );
        imagemLayout.setVerticalGroup(
            imagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(proxima_pergunta)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(resposta4)
                                .addComponent(resposta3)
                                .addComponent(resposta2)
                                .addComponent(resposta1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(imagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(resposta1)
                        .addGap(43, 43, 43)
                        .addComponent(resposta2)
                        .addGap(49, 49, 49)
                        .addComponent(resposta3)
                        .addGap(45, 45, 45)
                        .addComponent(resposta4))
                    .addComponent(imagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(proxima_pergunta)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resposta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resposta2ActionPerformed
        resposta1.setSelected(false);
        resposta2.setSelected(true);
        resposta3.setSelected(false);
        resposta4.setSelected(false);
        resposta_marcada = 1;
    }//GEN-LAST:event_resposta2ActionPerformed

    public void recomeca(){
        try {
            perguntaAtual = cont.ProximaPergunta();
        } catch (FimDeJogoException ex) {
            Logger.getLogger(Jogo.class.getName()).log(Level.SEVERE, null, ex);
        }
        bindingPergunta();
    }
    private void proxima_perguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proxima_perguntaActionPerformed
        try {
            if(resposta_marcada == -1){
                respostaEmBrancoDialog.setModal(true);
                respostaEmBrancoDialog.setVisible(true);
            }
            else{
                certa = cont.respostaCerta(resposta_marcada, perguntaAtual);
                if(certa == true){
                    respostaCertaMacaco.setModal(true);
                    respostaCertaMacaco.setVisible(true);
                }else{
                    respostaErradaMacaco.setModal(true);
                    respostaErradaMacaco.setVisible(true);
                }
                perguntaAtual = cont.ProximaPergunta();
                bindingPergunta();
            }
            
        } catch (FimDeJogoException ex) {
            finalDeJogoDialog.setTextOnFinal();
            finalDeJogoDialog.setVisible(true);
        }
    }//GEN-LAST:event_proxima_perguntaActionPerformed

    private void resposta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resposta1ActionPerformed
        resposta1.setSelected(true);
        resposta2.setSelected(false);
        resposta3.setSelected(false);
        resposta4.setSelected(false);
        resposta_marcada = 0;
    }//GEN-LAST:event_resposta1ActionPerformed

    private void resposta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resposta3ActionPerformed
        resposta1.setSelected(false);
        resposta2.setSelected(false);
        resposta3.setSelected(true);
        resposta4.setSelected(false);
        resposta_marcada = 2;
    }//GEN-LAST:event_resposta3ActionPerformed

    private void resposta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resposta4ActionPerformed
        resposta1.setSelected(false);
        resposta2.setSelected(false);
        resposta3.setSelected(false);
        resposta4.setSelected(true);
        resposta_marcada = 3;
    }//GEN-LAST:event_resposta4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogo().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel imagem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea pergunta;
    private javax.swing.JButton proxima_pergunta;
    private javax.swing.JRadioButton resposta1;
    private javax.swing.JRadioButton resposta2;
    private javax.swing.JRadioButton resposta3;
    private javax.swing.JRadioButton resposta4;
    // End of variables declaration//GEN-END:variables

    private void initDialogs() {
       respostaEmBrancoDialog = new RespostaEmBrancoDialog(new javax.swing.JFrame(), true);
       respostaEmBrancoDialog.setLocationRelativeTo(this);
       respostaEmBrancoDialog.setVisible(false);
       
       respostaCertaMacaco = new RespostaCertaMacaco(new javax.swing.JFrame(), true);
       respostaCertaMacaco.setLocationRelativeTo(this);
       respostaCertaMacaco.setVisible(false);
       
       respostaErradaMacaco = new RespostaErradaMacaco(new javax.swing.JFrame(), true);
       respostaErradaMacaco.setLocationRelativeTo(this);
       respostaErradaMacaco.setVisible(false);
       
       finalDeJogoDialog = new FinalDeJogoDialog(this, true);
       finalDeJogoDialog.setLocationRelativeTo(this);
       finalDeJogoDialog.setVisible(false);
    }
}
